name: Deploy to Kong Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Deck
      uses: kong/setup-deck@v1
      with:
        deck-version: "v1.38.1"
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Kong via decK
      run: |
        deck ping --kong-addr http://localhost:8001/
